version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
      - image: circleci/mongo:4.2.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    # working_directory: ~/spotifind

    steps:
      - checkout

      # TODO: figure out directory paths for caching
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd client && npm install
      - run: cd client && npm test

      - run: cd server && npm install
      - run: cd server && npm test
